services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./web:/app/web
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ${PWD}/postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d wikiparser_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
